name: Comments Transferor
description: Transfer all comments on an issue to another issue
author: noraworld
branding:
  icon: users
  color: blue

inputs:
  target_issue_repo:
    description: Select a repository with a username whose issue you want to transfer
    required: true
    default: ""
  target_issue_number:
    description: Select an issue number
    required: true
    default: ""
  personal_access_token:
    description: Specify your personal access token name stored in your repository
    required: false
    default: ""
  replace_twitter_short_url:
    description: Specify whether Twitter short URLs are replaced with the redirected ones
    required: false
    default: ""
  trim_empty_image_tag:
    description: Specify whether the markdown-styled empty image tags are trimmed
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Transfer comments
      run: node $GITHUB_ACTION_PATH/app.js
      shell: sh
      env:
        GITHUB_TOKEN:              ${{ github.token }}
        ISSUE_NUMBER:              ${{ github.event.issue.number }}
        GITHUB_ACTION_PATH:        ${{ github.action_path }}
        TARGET_ISSUE_REPO:         ${{ inputs.target_issue_repo }}
        TARGET_ISSUE_NUMBER:       ${{ inputs.target_issue_number }}
        PERSONAL_ACCESS_TOKEN:     ${{ inputs.personal_access_token }}
        REPLACE_TWITTER_SHORT_URL: ${{ inputs.replace_twitter_short_url }}
        TRIM_EMPTY_IMAGE_TAG:      ${{ inputs.trim_empty_image_tag }}
